#HOSTNAME = "192.168.1.173" # home
HOSTNAME = "192.168.19.45"  # phone hotspot
USERNAME = "humanoid39"
PASSWORD = "humanoid39"

# Phils data
#HOSTNAME = "192.168.137.59"
#USERNAME = "lwp26"
#PASSWORD = "lwp26"

#FIRMWARE_REMOTE_LOCATION = "/home/lwp26/Documents/firmware"

FIRMWARE_REMOTE_LOCATION = "/home/humanoid39/Documents/_firmware"
FIRMWARE_LOCAL_LOCATION = "C:\\Users\\andre\\Github\\humanoid-robot\\code\\_firmware"

ACCELEROMETER_REMOTE_LOCATION = "/home/humanoid39/Documents/_firmware/instruments"
ACCELEROMETER = 'accelerometer'

BAUDRATE = 115200
COM_PORT = "COM8"

ID = 39

GUI_WIDTH = 900
GUI_HEIGHT = 600

NUMBER_OF_SERVOS = 12

FORWARD = 1
BACKWARD = -1

LHR_IDX = 0
LHA_IDX = 1
LHE_IDX = 2
LK_IDX = 3
LAA_IDX = 4
LAE_IDX = 5

RHR_IDX = 6
RHA_IDX = 7
RHE_IDX = 8
RK_IDX = 9
RAA_IDX = 10
RAE_IDX = 11

LEFT_FOOT_X = 0
LEFT_FOOT_Y = 1
LEFT_FOOT_Z = 2

RIGHT_FOOT_X = 3
RIGHT_FOOT_Y = 4
RIGHT_FOOT_Z = 5

SHIFT_WEIGTH_MIN = -7
SHIFT_WEIGTH_MAX = 7
SHIFT_HEIGTH_MIN = -20
SHIFT_HEIGTH_MAX = -4

ALL_LEG_NAMES = ["lhr", "lha", "lhe", "lkk", "laa", "lae", "rhr", "rha", "rhe", "rkk", "raa", "rae"]
ALL_LEGS = [LHR_IDX, LHA_IDX, LHE_IDX, LK_IDX, LAA_IDX, LAE_IDX, RHR_IDX, RHA_IDX, RHE_IDX, RK_IDX, RAA_IDX, RAE_IDX]
ALL_POS = [LEFT_FOOT_X, LEFT_FOOT_Y, LEFT_FOOT_Z, RIGHT_FOOT_X, RIGHT_FOOT_Y, RIGHT_FOOT_Z]
MIN_POS = [-20, SHIFT_WEIGTH_MIN, SHIFT_HEIGTH_MIN, -20, SHIFT_WEIGTH_MIN, SHIFT_HEIGTH_MIN]
MAX_POS = [20, SHIFT_WEIGTH_MAX, SHIFT_HEIGTH_MAX, 20, SHIFT_WEIGTH_MAX, SHIFT_HEIGTH_MAX]

WALKING_HEIGHT = -18
FOOT_X_CENTER = -2