HOSTNAME = "192.168.1.173"
USERNAME = "humanoid39"
PASSWORD = "humanoid39"

# Phils data
#HOSTNAME = "192.168.137.59"
#USERNAME = "lwp26"
#PASSWORD = "lwp26"

#FIRMWARE_REMOTE_LOCATION = "/home/lwp26/Documents/firmware"

FIRMWARE_REMOTE_LOCATION = "/home/humanoid39/Documents/firmware"
FIRMWARE_LOCAL_LOCATION = "C:\\Users\\andre\\Github\\humanoid-robot\\code\\firmware"

GUI_WIDTH = 900
GUI_HEIGHT = 600

LHR_IDX = 0
LHA_IDX = 1
LHE_IDX = 2
LK_IDX = 3
LAA_IDX = 4
LAE_IDX = 5

RHR_IDX = 6
RHA_IDX = 7
RHE_IDX = 8
RK_IDX = 9
RAA_IDX = 10
RAE_IDX = 11

ALL_LEGS = [LHR_IDX, LHA_IDX, LHE_IDX, LK_IDX, LAA_IDX, LAE_IDX, RHR_IDX, RHA_IDX, RHE_IDX, RK_IDX, RAA_IDX, RAE_IDX]