[HUMANOID_VARS]
HOSTNAME : 192.168.1.160
#HOSTNAME = "192.168.1.160" # zero home wifi
#HOSTNAME = "10.245.36.30" # zero

HOSTNAME_CAMERA : 192.168.1.158
#HOSTNAME_CAMERA = "10.245.36.45" # phone camera hotspot
#HOSTNAME = "192.168.19.45"  

USERNAME : humanoid39zero
PASSWORD : humanoid39zero

USERNAME_CAMERA : humanoid39
PASSWORD_CAMERA : humanoid39

FIRMWARE_LOCAL_LOCATION : C:\\Users\\andre\\Github\\humanoid-robot\\code\\_firmware

FIRMWARE_REMOTE_LOCATION_CAMERA : /home/humanoid39/Documents/_firmware
FIRMWARE_REMOTE_LOCATION : /home/humanoid39zero/Documents/_firmware

INSTRUMENTS_REMOTE_LOCATION_CAMERA : /home/humanoid39/Documents/_firmware/instruments
INSTRUMENTS_REMOTE_LOCATION : /home/humanoid39zero/Documents/_firmware/instruments

walking_height = -14.5

foot_x_center = -1.5
foot_y_swing = -3
foot_y_push = -4
