[HUMANOID_VARS]
HOSTNAME : 192.168.50.179
#HOSTNAME = "192.168.1.160" # zero home wifi
#HOSTNAME = "10.79.11.30" # zero mobile hostpot
#HOSTNAME = "192.168.50.127"

HOSTNAME_CAMERA : 10.79.11.45
#HOSTNAME_CAMERA = "10.79.11.45" # phone camera hotspot
#HOSTNAME_CAMERA : 192.168.1.158 # camera home wifi

USERNAME : lwp2
PASSWORD : lwp2

USERNAME_CAMERA : lwp2
PASSWORD_CAMERA : lwp2

FIRMWARE_LOCAL_LOCATION : C:\\Users\\andre\\Github\\humanoid-robot\\code\\_firmware

FIRMWARE_REMOTE_LOCATION_CAMERA : /home/lwp2/Documents/_firmware
FIRMWARE_REMOTE_LOCATION : /home/lwp2/Documents/_firmware

INSTRUMENTS_REMOTE_LOCATION_CAMERA : /home/lwp2/Documents/_firmware/instruments
INSTRUMENTS_REMOTE_LOCATION : /home/lwp2/Documents/_firmware/instruments

walking_height = -14.5

foot_x_center = -1.0
foot_y_swing = -2
foot_y_push = -2
